DECLARE @StartDate DATETIME
DECLARE @EndDate DATETIME

-- Dynamic time constraints for CURRENT and PAST YEAR only
SET @StartDate = CAST(DATEADD(QUARTER, DATEDIFF(QUARTER, 0, GETDATE()) - 8, 0) AS DATETIME)
SET @EndDate = CAST(DATEADD(QUARTER, DATEDIFF(QUARTER, 0, GETDATE()) + 1, 0) AS DATETIME)

-- SQL query
SELECT
YEAR(DateTime) AS [Year],
'Q' + CONVERT(VARCHAR(1), DATEPART(QUARTER, DateTime)) AS [Quarter],
ROUND(AVG(ResponseTime.Availability), 2) AS AVERAGE_of_Availability,
Nodes.C02_PRIMARY_PROVIDER AS C02_PRIMARY_PROVIDER
FROM
Nodes
INNER JOIN
ResponseTime ON (Nodes.NodeID = ResponseTime.NodeID)
WHERE
C02_PRIMARY_PROVIDER IS Not NULL
AND
DateTime BETWEEN @StartDate AND @EndDate
GROUP BY
YEAR(DateTime),
DATEPART(QUARTER, DateTime),
Nodes.C02_PRIMARY_PROVIDER
ORDER BY
Nodes.C02_PRIMARY_PROVIDER,
YEAR(DateTime),
DATEPART(QUARTER, DateTime);
